export default function PrivacyPage() {
  return (
    <section className="stack page-container">
      <div className="card stack page-hero-card legal-page">
        <div className="section-eyebrow">Policy</div>
        <h1>Privacy</h1>

        <p className="muted page-intro">
          Solidity Quick Review is designed to provide contract analysis while respecting user privacy and minimizing
          unnecessary data collection. This section explains what information may be processed during normal operation
          of the service and how it is handled.
        </p>

        <div className="stack legal-copy">
          <h2>Report Privacy</h2>
          <p className="muted">Reports generated by the service are private by default.</p>
          <p className="muted">
            Access to analysis results is limited to the context in which the report was created. In most cases this
            means the report is accessible only to the wallet that initiated the analysis request.
          </p>
          <p className="muted">
            Reports are not publicly indexed or exposed by default. A report may become accessible to others only if
            one of the following actions occurs:
          </p>
          <ul className="stack muted">
            <li>the report is explicitly published</li>
            <li>a private share link is generated</li>
            <li>the owner chooses to disclose the report externally</li>
          </ul>
          <p className="muted">
            Private reports are intended to remain visible only to the report owner and the systems required to
            deliver the service.
          </p>
        </div>

        <div className="stack legal-copy">
          <h2>Wallet Authentication</h2>
          <p className="muted">Certain actions within the platform require wallet authentication.</p>
          <p className="muted">
            Wallet authentication is used for functions that involve ownership or account-linked operations. These
            actions may include:
          </p>
          <ul className="stack muted">
            <li>accessing report history</li>
            <li>verifying report ownership</li>
            <li>managing report visibility</li>
            <li>interacting with optional onchain receipts</li>
          </ul>
          <p className="muted">
            Authentication is performed using cryptographic signatures rather than traditional username and password
            systems. The service does not store private keys and does not request access to wallet funds.
          </p>
          <p className="muted">
            The wallet address may be associated with generated reports for the purpose of maintaining ownership and
            history records.
          </p>
        </div>

        <div className="stack legal-copy">
          <h2>Data Processing</h2>
          <p className="muted">
            When a contract snippet or verified contract address is submitted for analysis, the system processes the
            provided input in order to generate the security report.
          </p>
          <p className="muted">The service may temporarily process:</p>
          <ul className="stack muted">
            <li>submitted Solidity snippets</li>
            <li>verified contract source code retrieved from public explorers</li>
            <li>metadata necessary to generate the report</li>
          </ul>
          <p className="muted">This information is used strictly for analysis and report generation.</p>
          <p className="muted">The platform does not claim ownership over submitted contract code.</p>
        </div>

        <div className="stack legal-copy">
          <h2>Operational Logs and Telemetry</h2>
          <p className="muted">
            Operational logs and service telemetry may be collected in order to maintain system reliability,
            performance, and security.
          </p>
          <p className="muted">These records may include:</p>
          <ul className="stack muted">
            <li>request metadata</li>
            <li>system errors</li>
            <li>performance metrics</li>
            <li>security monitoring events</li>
          </ul>
          <p className="muted">
            Operational logs are used solely to maintain and improve the service. They are not used for advertising or
            behavioral tracking.
          </p>
          <p className="muted">
            Where possible, logging systems are configured to avoid storing unnecessary user-submitted content.
          </p>
        </div>

        <div className="stack legal-copy">
          <h2>Security Considerations</h2>
          <p className="muted">
            Reasonable technical measures are used to protect the integrity and confidentiality of processed data.
            These measures may include access controls, infrastructure protections, and monitoring systems designed to
            detect abnormal activity.
          </p>
          <p className="muted">
            However, no internet service can guarantee absolute security. Users should avoid submitting sensitive or
            confidential proprietary code unless they understand and accept the risks inherent to any online analysis
            service.
          </p>
        </div>

        <div className="stack legal-copy">
          <h2>Third-Party Infrastructure</h2>
          <p className="muted">
            The service may rely on external infrastructure providers in order to operate, such as hosting,
            networking, or blockchain infrastructure services.
          </p>
          <p className="muted">
            These providers may process limited operational data required for the platform to function. Such
            processing occurs under the infrastructure provider&apos;s own security and privacy standards.
          </p>
        </div>

        <div className="stack legal-copy">
          <h2>Data Retention</h2>
          <p className="muted">
            Reports and related metadata may be retained for the purpose of providing history features and maintaining
            report ownership.
          </p>
          <p className="muted">
            Operational logs and diagnostic information may be retained for a limited period to support system
            maintenance, debugging, and abuse prevention.
          </p>
          <p className="muted">Retention policies may change over time as the service evolves.</p>
        </div>

        <div className="stack legal-copy">
          <h2>Changes to This Policy</h2>
          <p className="muted">
            This privacy section may be updated as the platform develops new features or modifies how data is
            processed.
          </p>
          <p className="muted">Material changes may be reflected through updates to this page.</p>
          <p className="muted">
            Continued use of the service after updates indicates acceptance of the revised privacy terms.
          </p>
        </div>
      </div>
    </section>
  );
}
